### ISSUE TITLE
Deploy application on Heroku

### ISSUE THREAD

**Issue by bonniesimon** [bonniesimon/neeto-ui-challenge-bonniesimon#17]
Deployed at [bonnie-neetoui-challenge](https://bonnie-neetoui-challenge.herokuapp.com)
Can be logged in using:
Username : oliver@example.com
Password : welcome

@yedhink  Please review

**Comment by yedhink** [comment]
@bonniesimon LGTM. Mark this task as completed and continue with the next task.
